<?php
$form = $this->changePasswordForm;
/** @var Zend\Form\Form $form */

?>
<div class="container">
    <div id="loginbox" style="margin-top:50px;" class="mainbox col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
        <div class="panel panel-info" >
            <div class="panel-heading">
                <div class="panel-title"><?= $this->translate('Change password'); ?></div>
            </div>

            <div style="padding-top:30px" class="panel-body" >

                <div id="login-alert" class="alert alert-danger col-sm-12">
                    <p>Error 1</p>
                </div>

                <?= $this->form()->openTag($form) ?>


                <div style="margin-bottom: 25px" class="input-group">
                    <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
                    <?= $this->formRow($form->get('password')->setAttribute('class', 'form-control')); ?>
                </div>

                <div style="margin-bottom: 25px" class="input-group">
                    <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
                    <?= $this->formRow($form->get('passwordAgain')->setAttribute('class', 'form-control')); ?>
                </div>


                <div style="margin-top:10px" class="form-group">
                    <!-- Button -->

                    <div class="col-sm-12 controls">
                        <button id="btn-login" class="btn btn-primary"><?= $this->transate('Change password'); ?></button>
                    </div>
                </div>

                <?= $this->form()->closeTag($form) ?>
            </div>
        </div>
    </div>
</div>