<?php
$loginForm = $this->loginForm;
/** @var Zend\Form\Form $loginForm */

?>
<div class="container">
    <div id="loginbox" style="margin-top:50px;" class="mainbox col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
        <div class="panel panel-info" >
            <div class="panel-heading">
                <div class="panel-title">Sign In</div>
                <div style="float:right; font-size: 80%; position: relative; top:-10px"><a href="#">Forgot password?</a></div>
            </div>

            <div style="padding-top:30px" class="panel-body" >

                <div style="display:none" id="login-alert" class="alert alert-danger col-sm-12"></div>

                    <?= $this->form()->openTag($loginForm) ?>


                    <div style="margin-bottom: 25px" class="input-group">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                        <?= $this->formRow($loginForm->get('username')->setAttribute('class', 'form-control')); ?>
                    </div>

                    <div style="margin-bottom: 25px" class="input-group">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
                        <?= $this->formRow($loginForm->get('password')->setAttribute('class', 'form-control')); ?>
                    </div>


                    <div style="margin-top:10px" class="form-group">
                        <!-- Button -->

                        <div class="col-sm-12 controls">
                            <button id="btn-login" href="#" class="btn btn-primary">Login</button>
                        </div>
                    </div>

                <?= $this->form()->closeTag($loginForm) ?>
            </div>
        </div>
    </div>
</div>
    