<?php
$form = $this->recoveryForm;
/** @var Zend\Form\Form $form */

?>
<div class="container">
    <div id="loginbox" style="margin-top:50px;" class="mainbox col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
        <div class="panel panel-info" >

            <div class="panel-heading">
                <div class="panel-title"><?= $this->translate('Request password change'); ?></div>
            </div>

            <div style="padding-top:30px" class="panel-body" >
                <?= $this->form()->openTag($form) ?>
                <div id="login-alert" class="alert alert-danger col-sm-12">sdsad</div>
                <div id="login-alert" class="alert alert-info col-sm-12">
                    <?= $this->translate('Please fill in username to change password'); ?>
                </div>




                <div style="margin-bottom: 25px" class="input-group">
                    <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                    <?= $this->formRow($form->get('username')->setAttribute('class', 'form-control')); ?>
                </div>

                <div style="margin-top:10px" class="form-group">
                    <!-- Button -->

                    <div class="col-sm-12 controls">
                        <button id="btn-login" class="btn btn-primary"><?= $this->translate('Recover password'); ?></button>
                    </div>
                </div>

                <?= $this->form()->closeTag($form) ?>
            </div>
        </div>
    </div>
</div>