<?php
$form = $this->resetForm;
/** @var Zend\Form\Form $form */

$flashMessenger = $this->flashMessenger();
/** @var Zend\View\Helper\FlashMessenger $flashMessenger */
?>
<div class="container">
    <div id="loginbox" style="margin-top:50px;" class="mainbox col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
        <div class="panel panel-info">
            <div class="panel-heading">
                <div class="panel-title"><?= $this->translate('Set new password'); ?></div>
            </div>

            <div style="padding-top:30px" class="panel-body" >
                <?= $this->form()->openTag($form) ?>

                <?php if ($flashMessenger->getPluginFlashMessenger()->hasCurrentErrorMessages()) { ?>
                <div class="alert alert-danger col-sm-12">
                    <?= $flashMessenger->render('error'); ?>
                </div>
                <?php } ?>

                <?php if ($flashMessenger->getPluginFlashMessenger()->hasCurrentSuccessMessages()) { ?>
                    <div class="alert alert-success col-sm-12">
                        <?= $flashMessenger->render('success'); ?>
                    </div>
                <?php } ?>

                <div class="row">
                    <div class="col-md-12">
                        <div style="margin-bottom: 25px" class="input-group">
                            <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
                            <?= $this->formRow($form->get('password')->setAttribute('class', 'form-control')); ?>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-12">
                        <div style="margin-bottom: 25px" class="input-group">
                            <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
                            <?= $this->formRow($form->get('passwordAgain')->setAttribute('class', 'form-control')); ?>
                        </div>
                    </div>
                </div>



                <div style="margin-top:10px" class="form-group">
                    <!-- Button -->

                    <div class="col-sm-12 controls">
                        <a href="<?php echo $this->url('bd_authentication_login'); ?>" class="btn btn-default"><?= $this->translate('Back'); ?></a>
                        <button id="btn-login" class="btn btn-primary"><?= $this->translate('Recover password'); ?></button>
                    </div>
                </div>

                <?= $this->form()->closeTag($form) ?>
            </div>
        </div>
    </div>
</div>